### ISSUE TITLE
Get may need support for named parameters

### ISSUE THREAD

**Issue by object** [ThatRendle/Simple.Data#124]
As I mentioned in my mail regarding OData issues, in case resource key consists of multiple properties, support for named paramaters in Get (similar to Insert) will be benefitial:

In addition to Get(object[] keyValues)
also Get(IDictionary<string, object> keyValues)

Then client code can issue commands db.Users.Get(FirstName: "Jim", LastName: "Smith").

OData requires named parameters for compound keys.

If you agree with this, I can make a change and send a pull request.

**Comment by ThatRendle** [comment]
I'm a bit unsure about this. Is there any standard OData way that you could discover the names for the compound key names from metadata or fetching a single random record? Then you could apply that naming automagically. That would fit better with the cross-platform nature of the thing, since for the ADO and MongoDB adapters having named parameters in the Get method would be confusing; it would basically have the same signature and meaning as FindBy(FirstName: "Jim", LastName: "Smith").

If that's not possible, then we'll have to implement your approach, in which case I would greatly appreciate a pull request.

**Comment by object** [comment]
Of course for ADO and some other adapters named parameters are unnecessary, although I see some convenience in being able to specify orderDeatils.Get(OrderID: 1, ProductID: 2) in addition to just orderDetails.Get(1,2), so people won't need to remember the order of key parameters.

For OData this may give another advantage: no need to make a roundtrip to a server to fetch metadata prior to sending the request. This will be good for ad-hoc OData requests: client can fetch data in a single network roundtrip without handshaking. However, if for other reasons OData adapter will read metadata anyway (and I suspect there will be other reasons), this won't be significant.

AFAIK it's possible to fetch key parameter order from an OData server, but let me come back to this point during the weekend.

**Comment by ThatRendle** [comment]
Metadata only has to be fetched once, then you can cache it locally (much like the ADO adapter does with DB schema). For web apps in particular this is a negligible costs, if something is held in a static member it hangs around forever.

**Comment by object** [comment]
Agree. I've reconsidered my point: Get should not look like a variation of Find. So I'll stick to parameterless Get.
