### ISSUE TITLE
1 field

### ISSUE THREAD

**Issue by nkaiseng** [ThatRendle/Simple.Data#137]
How do i get only 1 field

I only want to return  the password for this user

 var password = db.defaultsuser.FindByUsername("safi");

**Comment by ThatRendle** [comment]
Just use the password "property":

var password = db.defaultsuser.FindByUsername("safi").Password; // Beware
NullReferenceException if safi doesn't exist!

If you want to force the underlying SELECT to only /fetch/ the password:

var password =
db.defaultsuser.FindAllByUsername("safi").Select(db.defaultsuser.password).Take(1).ToScalarValue<string>();

But that's probably overkill, I'd just use the first version.

There's no Select method when using FindBy since it returns a SimpleRecord,
not a SimpleQuery.

Cheers,
Mark

On Thu, Jan 19, 2012 at 8:53 AM, nkaiseng <
reply@reply.github.com

**Comment by marcioalthmann** [comment]
And a collection of fields its possible, like LINQ from n in blablabla select new {} ?

**Comment by ThatRendle** [comment]
When selecting multiple rows, you can use .Select(db.Foo.Id, db.Foo.Description). No way to do on FindBy or Get, since those return the record directly, but you can always do a FindAllBy with .Take(1).
