### ISSUE TITLE
"Like" does not work due to parameter's length

### ISSUE THREAD

**Issue by matteobaglini** [ThatRendle/Simple.Data#148]
given the following table and data (SQL Server):

CREATE TABLE [dbo].[Pers]([Group] [char]%286%29 NULL)
INSERT INTO [dbo].[Pers]([Group])VALUES ('100004')
INSERT INTO [dbo].[Pers]([Group])VALUES ('200000')

this snippet does not find anything:
var per in db.dbo.Pers.FindAll(db.dbo.Pers.Grup.Like("%4"))

I've investigated with the SQL Server Profiler and I've found that the cause was the parameter's length equal to 6 instead of 2.
exec sp_executesql N'select [dbo].[Pers].[Group] from [dbo].[Pers] WHERE [dbo].[Pers].[Group] LIKE @p1',N'@p1 char(6)',@p1='%4    '

**Comment by richardhopton** [comment]
That is likely because you have used CHAR which is whitespace padded. Using VARCHAR should help with this.  Unless you have a specific reason to use CHAR I'd recommend switching.

---

From: bmatte
Sent: 13/02/2012 13:11
To: richardhopton
Subject: [Simple.Data] "Like" does not work due to parameter's length (#148)

given the following table and data (SQL Server):

CREATE TABLE [dbo].[Pers]([Group] [char]%286%29 NULL)
INSERT INTO [dbo].[Pers]([Group])VALUES ('100004')
INSERT INTO [dbo].[Pers]([Group])VALUES ('200000')

this snippet does not find anything:
var per in db.dbo.Pers.FindAll(db.dbo.Pers.Grup.Like("%4"))

I've investigated with the SQL Server Profiler and I've found that the cause was the parameter's length equal to 6 instead of 2.
exec sp_executesql N'select [dbo].[Pers].[Group] from [dbo].[Pers] WHERE [dbo].[Pers].[Group] LIKE @p1',N'@p1 char(6)',@p1='%4    '

---

Reply to this email directly or view it on GitHub:
https://github.com/markrendle/Simple.Data/issues/148

**Comment by matteobaglini** [comment]
@richardhopton thanks for the reply. 
I know that VARCHAR is better but in this case I'm working with a legacy db and I can't change it's schema.

**Comment by richardhopton** [comment]
Ok will have to look into this - thanks for raising the issue.  Not sure of a work around except maybe creating a passthrough view that casts the field to VARCHAR, and a "instead of " UPDATE & INSERT triggers to push changes back into the table.

**Comment by ThatRendle** [comment]
I added a special-case for char and nchar types in the parameter factory.

**Comment by matteobaglini** [comment]
@markrendle great!
