### ISSUE TITLE
Possible Bug in ForeignKeyCollection

### ISSUE THREAD

**Issue by NotMyself** [ThatRendle/Simple.Data#15]
I just checked in a test that demonstrates a bug that I am currently running into. I have a table with two foreign keys and the ForeignKeyCollection seems to be bonking because the collection uses only the master table ObjectName as a key for the collection. You can see the test here: https://github.com/NotMyself/Simple.Data/blob/master/Simple.Data.Ado.Test/ForeignKeyCollectionTests.cs

Are my assumptions correct? I'll try to submit a patch but I will need to dig a little deeper into how the key collection is used and referenced by the consuming code.

**Comment by ThatRendle** [comment]
This behaviour is by design.

ForeignKeyCollection is only used as an instance variable within a Table object, so the use of the Master table as its key is only a problem if a table has two foreign keys pointing to the same table. That might be valid in pure database terms, but since Simple.Data is trying to use the referential integrity info to infer lazy-loading or joining at runtime, it wouldn't be able to make sense of that situation anyway.

**Comment by NotMyself** [comment]
hrm maybe i am misunderstanding what master & detail mean in the context of a FK then.

https://github.com/NotMyself/Simple.Data/blob/master/Simple.Data.Sqlite/SqliteSchemaProvider.cs#L68

**Comment by ThatRendle** [comment]
Yes, I think you are. The table parameter passed to GetForeignKeys refers to the detail table, not the master.

**Comment by NotMyself** [comment]
gotcha, thanks
