### ISSUE TITLE
For the love of god how do I get at the connection?

### ISSUE THREAD

**Issue by NotMyself** [ThatRendle/Simple.Data#42]
Hi Mark,

I have been trying to get my SQLite provider updated and have been having little luck. It looks like the ProviderLocator is no longer a static class that I can use to weasel my way into the active connection. You can see here why I need to get at the connection:

https://github.com/NotMyself/Simple.Data/blob/master/Simple.Data.SqliteTests/InMemoryUsageTests.cs#L20

I am basically using the connection to inject some tables and test data into an im memory DB prior to doing some tests. Have any hints or thoughts on a better way to accomplish this?

Remember that if the connection is closed the DB is destroyed and if I open up two connections.... sqlite is kind enough to create two DBs for me.

/stuck in seattle
Bobby

**Comment by ThatRendle** [comment]
I'll have a look into it this weekend.

-----Original Message-----
From: NotMyself
Sent: 22 April 2011 15:29
To: mark@markrendle.net
Subject: [GitHub] For the love of god how do I get at the connection? [markrendle/Simple.Data GH-42]

Hi Mark,

I have been trying to get my SQLite provider updated and have been having little luck. It looks like the ProviderLocator is no longer a static class that I can use to weasel my way into the active connection. You can see here why I need to get at the connection:

https://github.com/NotMyself/Simple.Data/blob/master/Simple.Data.SqliteTests/InMemoryUsageTests.cs#L20

I am basically using the connection to inject some tables and test data into an im memory DB prior to doing some tests. Have any hints or thoughts on a better way to accomplish this?

Remember that if the connection is closed the DB is destroyed and if I open up two connections.... sqlite is kind enough to create two DBs for me.

/stuck in seattle
Bobby

## 

Reply to this email directly or view it on GitHub:
https://github.com/markrendle/Simple.Data/issues/42

**Comment by ThatRendle** [comment]
Hi. You need to add a reference to the Simple.Data.TestHelper project, which adds extension methods to expose some internals for testing purposes only. Then add

using Simple.Data.TestHelper;

and change line 20 to

var adapter = ((Database)db).GetAdapter() as AdoAdapter;
connection = adapter.ConnectionProvider.CreateConnection();

And you should be good. Let me know how that works for you.

**Comment by NotMyself** [comment]
Hrm that seems smelly to me. I wouldn't want my provider to have a dependency on your testing lib. Theoretically someone could want to use an in memory store when they are not testing.

But I can use this as a work around to get back up to speed with you.

**Comment by ThatRendle** [comment]
The in-memory feature is pretty specific to SQLite, so I'd suggest adding a public type to your assembly to expose the IDbConnection which is returned by your Provider. It wouldn't be right to expose an ADO object directly through Simple.Data core since there is not necessarily an ADO back-end. I guess the connection could be exposed as a public member from the Ado adapter assembly. I'll poke around the code and see if there's a sensible place to put it.

**Comment by NotMyself** [comment]
I completely agree with you. It is a sqlite specific concern. I'll see how far I can get with your advice. My objection is to adding a dependency between my sqlite provider and the testing library. The provider it's self is a production assembly in my eyes and adding a testing dependency feels dirty. Let me play with it a bit and ill get back to you with suggestions.

My current feeling is you are hiding the connection to well. I understand you are programming defensively, but every move you make to protect me from myself frustrates me. Don't program like a Microsoft developer. I like to run with scissors and I think the ppl who use this library do as well. 8)

**Comment by ThatRendle** [comment]
My problem is that there isn't necessarily a connection. If somebody is using the Simple.Data.MongoDB adapter, for example, then exposing an IDbConnection through the public API (i.e. for end-users, rather than Provider authors) is meaningless and violates Liskov. And I'm hoping there will be adapters for lots of NoSQL stores; I'm releasing one for Azure Table Storage soon, and then evolving that code into an OData adapter.

You shouldn't need to depend on the TestHelper library for what you're doing. You already have access to the connection, because you own the IConnectionProvider which is "creating" it. So you could expose a method to return that same connection within the Simple.Data.Sqlite assembly, maybe taking the connection string as a parameter?

The alternative, I suppose, is to add a GetAdapter() method to the Database class, and then developers could call that and cast it to the type of adapter they know they're using, which would then have the relevant properties on it, without breaking LSP.

**Comment by ThatRendle** [comment]
I've made the GetAdapter method on the DataStrategy (i.e. Database and SimpleTransaction) public, so you can now use:

((AdoAdapter)_db.GetAdapter()).ConnectionProvider.CreateConnection()

which should, for your in-memory mode, just return the persistent connection as an IDbConnection.
