### ISSUE TITLE
Pluralisation inference

### ISSUE THREAD

**Issue by cairey** [ThatRendle/Simple.Data#64]
How about away to switch on pluralisation inference? For example, I like my table names to be singular e.g. "Customer". So my query looks like "db.Customer", I would like "db.Customers"

**Comment by ThatRendle** [comment]
Yes, it does that :)

Mark

**Comment by cairey** [comment]
Good to see, you are ahead of me. Bah I should have tested it!

**Comment by jamezor** [comment]
Can I ask if any improvements were planned in this area? Currently my Company table needs to be accessed via Companys which is not quite right :)

As per http://stackoverflow.com/questions/475705/pluralize-singularize there is a few options to avoid rolling your own - System.Data.Entity.Design.PluralizationServices.PluralizationService may be a good bet since it's included in the framework already, or Castle project has the Inflector class (buried deep in ActiveRecord) which looks pretty comprehensive.
- James

**Comment by ThatRendle** [comment]
I have added an extension point in 0.7.2. There is a new public interface in the Simple.Data library called IPluralizer which can be easily implemented using whichever of the libraries mentioned in that StackOverflow thread.

Here's a sample implementation using the Entity Framework class:

```
class EntityPluralizer : IPluralizer
{
    private readonly PluralizationService _pluralizationService =
        PluralizationService.CreateService(CultureInfo.CurrentCulture);

    public bool IsPlural(string word)
    {
        return _pluralizationService.IsPlural(word);
    }

    public bool IsSingular(string word)
    {
        return _pluralizationService.IsSingular(word);
    }

    public string Pluralize(string word)
    {
        bool upper = (word.IsAllUpperCase());
        word = _pluralizationService.Pluralize(word);
        return upper ? word.ToUpper(_pluralizationService.Culture) : word;
    }

    public string Singularize(string word)
    {
        return _pluralizationService.Singularize(word);
    }
}
```

To apply a custom IPluralizer, there is a static SetPluralizer method on the Database class.

The test suite confirms that this implementation will resolve db.Companies to a table called Company.

I am releasing 0.7.2 on NuGet early this afternoon.

Cheers,
Mark
