### ISSUE TITLE
Make ExpressionHelper public

### ISSUE THREAD

**Issue by tyronegroves** [ThatRendle/Simple.Data#67]
I want to be able to do something like this:

 db.Update(tableName, values, expression);

The only way I can see to create "expression" is like this:

ExpressionHelper.CriteriaDictionaryToExpression(tableName, criteria);

but the ExpressionHelper is internal and ObjectReference is internal too.

Can you make ExpressionHelper public?

**Comment by ThatRendle** [comment]
You can't do anything like that. Why do you want to? Can you explain what it is you're actually trying to do?

**Comment by tyronegroves** [comment]
Explaining why would take a while, but this does work and all that needs to be done is make the ExpressionHelper public.  How would you dynamically create a where clause?

**Comment by tyronegroves** [comment]
The db.Update() method is public but I can create an expression object

**Comment by ThatRendle** [comment]
Right, the problem was that the Update method was public, which understandably caused you to think it was for general consumption, but it wasn't. So I've fixed that, and all those methods are now marked as internal.

Now then.

You can dynamically reference tables and columns by using string indexers instead of dynamic properties. These two lines are semantically equivalent:

```
db.Foo.Bar == 1;
db["Foo"]["Bar"] == 1;
```

The approved form of what I think you're trying to do is:

```
db[tableName].UpdateAll(db[tableName][keyColumnName] == 1, Foo: "this", Bar: "that");
```

What you can't currently do is dynamically create the "set" values, but I have just pushed a commit which adds that support via a Dictionary:

```
var newValues = new Dictionary<string, object> { { "Foo", "this" }, { "Bar", "that" } };
db[tableName].UpdateAll(db[tableName][keyColumnName] == 1, newValues);
```

Will that meet your requirement?

**Comment by tyronegroves** [comment]
I will try it and get back to you.  But thanks in advance.

**Comment by tyronegroves** [comment]
How would I handle multiple key columns?  And what about deletes and exists?

**Comment by tyronegroves** [comment]
Its all jack now!!!!!

**Comment by geoffreysmith** [comment]
Yes, the SchemaProvider is now gone.

**Comment by ThatRendle** [comment]
I don't know what that means.

**Comment by ThatRendle** [comment]
Or that.

**Comment by ThatRendle** [comment]
In what sense?

**Comment by geoffreysmith** [comment]
Sorry that was a pretty crummy bug report. After you made all those methods internal, this suddenly failed (or could be the result of my own code, I no longer have your latest assemblies in my project, but 99% certain I did not change any code):

db.GetAdapter().SchemaProvider as ISchemaProvider;

As for Tyrone's comment, he means that your code works until you have two primary key columns on a table, it will only pick up the first primary key column. 

If you move the methods from internal to public, everything works fine. I guess we're not really seeing the motivation behind moving the access rights to internal.

Great project, keep up the good work!

**Comment by ThatRendle** [comment]
The SchemaProvider property is only on the AdoAdapter, so you'll need
to cast the return from db.GetAdapter() as Simple.Data.AdoAdapter.

Things are marked internal or private when they are not intended to be
part of the API, so that I can make implementation changes without
breaking people's production code. For example, the methods on the
DataStrategy class which I have changed to internal only exist to
support the duality of database and transaction; the correct way to
access Insert/Update/Delete is through the dynamic methods on the
Table objects.

Finding the right balance here is tricky, but I assure you that I am
not trying to be obstructive.

Tyrone, if you could open a new issue for the compound primary key
problem with a couple more details I'll look into it.

Cheers,
Mark

Sent from my iPad

On 12 Jul 2011, at 00:37, geoffreysmith
reply@reply.github.com
wrote:
