### ISSUE TITLE
Support for default key in FindOne

### ISSUE THREAD

**Issue by object** [ThatRendle/Simple.Data#86]
There are certain data providers that allow looking up data by a primary key without specifying the key name. The most trivial example is .NET Dictionary class. Another example is OData provider. It supports both names and unnamed filters:

/Suppliers?$filter=Address/City eq 'Redmond'

/Categories(1)

The second example shows primary key-based lookup: Categories has a key CategoryID, but it does not need to be specified, OData provider will understand this notation and generate query that looks up by CategoryID.

Currently Simple.Data requires specification of the lookup key, but it would be handy if had an optional support for default keys, so client application could use syntax similar to this:

db.Categories.FindOne(1);

This notation could be useful even for SQL-based providers. And compound keys could be specified using multiple arguments:

db.Persons.FindOne("John", "Smilth"); // assuming there is a PK on FirstName + LastName.

**Comment by ThatRendle** [comment]
I have thought about adding a Get() method which would work like that.
I think all the data stores that are currently supported have the
concept of a default key; MongoDB has IDs, and Azure Tables would
support it with a Partition Key and Row Key combination.

So I will add it, although due to semantic versioning it's going to
mean a 0.10 release. Never mind.

Mark

Sent from my iPad (until Win8 gets a mail app)

On 24 Sep 2011, at 07:36, Vagif Abilov
reply@reply.github.com
wrote:

**Comment by object** [comment]
Yes, introducing Get() sounds good. Will help OData provider (and simplify working with others).
Of course it will require new version number.

**Comment by ThatRendle** [comment]
Get method added in 0.11
